---
title: "Dashboard - NYC Restaurant Inspections"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
data("rest_inspec")
```

```{r}
nyc_inspections = rest_inspec %>%
  separate(inspection_date, into = c("year", "month", "day")) %>% 
  filter(as.numeric(year) == 2017, month == "06") %>% 
  select(boro, critical_flag, cuisine_description, score, zipcode) %>% drop_na()
```



Column {data-width=650}
-----------------------------------------------------------------------

### Chart A - Average Inspection Score Per Zip Code in Manhattan (Scatterplot)

```{r}
nyc_inspections %>% 
  filter(boro == "MANHATTAN") %>% 
  group_by(zipcode) %>% 
  mutate(average_score = mean(score),
         zipcode = as.factor(zipcode),
         text_label = str_c("Average Score: ", average_score, "\nZip Code: ",
         zipcode, "\nStatus: ", critical_flag)) %>% 
  plot_ly(y = ~average_score, x = ~ zipcode, color = ~critical_flag, text = ~text_label, type = "scatter", mode = "markers") %>% 
  layout(
    xaxis = list(title = "Zipcode"),
    yaxis = list(title = "Inspection Score")) 

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B - Inspection Scores by Borough (Boxplot)

```{r}
nyc_inspections %>% 
  mutate(boro= fct_reorder(boro, score)) %>%
  plot_ly(x =~boro, y = ~score, type = "box", color = ~boro, colors = "viridis") %>% 
  layout(
    xaxis = list(title = "Borough"),
    yaxis = list(title = "Inspection Score")) 
```

### Chart C - Inspection Scores of Pizza and Dessert Restaurants (Bar Graph)

```{r}
nyc_inspections %>% 
  filter(cuisine_description == "Pizza"|cuisine_description == "Donuts"|cuisine_description == "Ice Cream, Gelato, Yogurt, Ices"|cuisine_description == "Bakery") %>% 
  plot_ly(x =~cuisine_description, y = ~score, type = "bar", color = ~cuisine_description, colors = "viridis",  width = 0.0000001) %>% 
  layout(
    xaxis = list(title = "Food Type"),
    yaxis = list(title = "Inspection Score", tickformat = ",")) 
```
